services:
  mongodb:
    image: mongo:8.0
    networks:
      - mongodb
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminuser
      MONGO_INITDB_ROOT_PASSWORD: __mongo_password__
    volumes:
      - /volume_01/mongodb/db:/data/db
      - /volume_01/mongodb/configdb:/data/configdb

networks:
  mongodb:
    name: mongodb
