services:
  mongodb:
    image: mongo:8.0
    networks:
      - mongodb
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ${VOLUME_PATH}/mongodb/db:/data/db
      - ${VOLUME_PATH}/mongodb/configdb:/data/configdb

networks:
  mongodb:
    name: mongodb
