# Define the entry points to listen on port 80 for HTTP
entryPoints:
  webservice:
    address: ":80"  # Listen on port 80 for HTTP requests
    http:
      middlewares:
        - ratelimiter@file
        - inflightlimiter@file
        - responseCompressor@file

# Enable access logs
log:
  level: DEBUG
  format: common
  filePath: "/dev/stdout"  # Logs to stdout

# Enable the Traefik dashboard (optional, for debugging purposes)
api:
  dashboard: true # the dashboard view
  insecure: false # insecure dashboard (for local testing exposes the dashboard on port 8080, don't use in production)
  basePath: "/"   # base path for API and dashboard (`/api` and `/dashboard`)

# Enable health-check service
ping:
  manualRouting: true

providers:
  file:
    directory: /etc/traefik-dynamic
